name: Kwiki-URLBlock
version: 0.05
abstract: Blocks edit based on added URLs
author: Jon Aslund <aslund.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.37
  URI::Find: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.34
